---
run:
  timeout: 3m
linters:
  disable-all: true
  enable:
    - asciicheck
    - deadcode
    - depguard
    - dupl
    - errcheck
    - exhaustive
    - exportloopref
    - funlen
    - gci
    - goconst
    - gocritic
    # - godot
    - godox
    - goheader
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - ifshort
    - lll
    - megacheck
    - misspell
    # - nlreturn
    - nolintlint
    - revive
    - staticcheck
    - structcheck
    - tagliatelle
    - testpackage
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
linters-settings:
  funlen:
    lines: 100
    statements: 70
  lll:
    line-length: 100
