---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: hpessa-exporter
    openshift.io/cluster-monitoring: "true"
  name: openshift-storage-hpessa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: hpessa-exporter
    app.kubernetes.io/part-of: openshift-storage-hpessa
  name: hpessa-exporter
  namespace: openshift-storage-hpessa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: hpessa-exporter
  name: hpessa-exporter
  namespace: openshift-storage-hpessa
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - daemonsets
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: hpessa-exporter
  name: hpessa-exporter
rules:
  - apiGroups:
      - apps
    resources:
      - daemonsets
    verbs:
      - get
      - list
      - create
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: hpessa-exporter
  name: hpessa-exporter
  namespace: openshift-storage-hpessa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hpessa-exporter
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: openshift-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: hpessa-exporter
  name: hpessa-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hpessa-exporter
subjects:
  - kind: ServiceAccount
    name: hpessa-exporter
    namespace: openshift-storage-hpessa
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: hpessa-exporter
    app.kubernetes.io/part-of: openshift-storage-hpessa
  name: hpessa-exporter
  namespace: openshift-storage-hpessa
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: hpessa-exporter
      app.kubernetes.io/part-of: openshift-storage-hpessa
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/name: hpessa-exporter
        app.kubernetes.io/part-of: openshift-storage-hpessa
    spec:
      containers:
        - args:
            - --port=8080
          command:
            - /hpessa-exporter
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          image: quay.io/ssharon/hpessa-exporter:latest
          imagePullPolicy: Always
          name: hpessa-exporter
          ports:
            - containerPort: 8080
              name: metrics
              protocol: TCP
          resources:
            requests:
              cpu: 8m
              memory: 32Mi
          securityContext:
            privileged: true
            runAsUser: 0
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - mountPath: /host/sys
              mountPropagation: HostToContainer
              name: sys
              readOnly: true
            - mountPath: /host/dev
              mountPropagation: HostToContainer
              name: dev
              readOnly: true
            - mountPath: /opt
              mountPropagation: HostToContainer
              name: opt
              readOnly: true
            - mountPath: /lib64
              mountPropagation: HostToContainer
              name: lib64
              readOnly: true
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: hpessa-exporter
      tolerations:
        - operator: Exists
      volumes:
        - hostPath:
            path: /sys
          name: sys
        - hostPath:
            path: /dev
          name: dev
        - hostPath:
            path: /opt
          name: opt
        - hostPath:
            path: /lib64
          name: lib64
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 10%
    type: RollingUpdate
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app.kubernetes.io/name: hpessa-exporter
    app.kubernetes.io/part-of: openshift-storage-hpessa
  name: hpessa-exporter-monitor
  namespace: openshift-storage-hpessa
spec:
  namespaceSelector:
    matchNames:
      - openshift-storage-hpessa
  podMetricsEndpoints:
    - interval: 3m
      path: /metrics
      port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: hpessa-exporter
      app.kubernetes.io/part-of: openshift-storage-hpessa
