---
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - podmonitor.yaml
  - daemonset.yaml
namespace: openshift-storage-hpessa
commonLabels:
  app.kubernetes.io/name: hpessa-exporter
configurations:
  - kustomizeconfig.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: hpessa-exporter
    newName: quay.io/ssharon/ hpessa-exporter
    newTag: latest
