---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app.kubernetes.io/name: hpessa-exporter
    app.kubernetes.io/part-of: openshift-storage-hpessa
  name: hpessa-exporter-monitor
  namespace: openshift-storage-hpessa
spec:
  namespaceSelector:
    matchNames:
      - openshift-storage-hpessa
  selector:
    matchLabels:
      app.kubernetes.io/name: hpessa-exporter
      app.kubernetes.io/part-of: openshift-storage-hpessa
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 3m
