---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hpessa-exporter
  namespace: openshift-hpessa-exporter
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: hpessa-exporter
    app.kubernetes.io/part-of: openshift-hpessa-exporter
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
    verbs:
      - get
      - list
      - create
      - delete
  - apiGroups:
      - ""
    resources:
      - services
      - daemonsets
      - endpoints
      - pods
      - pods/exec
      - pods/log
    verbs:
      - get
      - list
      - create
      - delete
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - prometheusrules
      - servicemonitors
      - podmonitors
    verbs:
      - get
      - list
      - create
      - delete
      - update
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    verbs:
      - create
      - delete
      - get
      - use
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hpessa-exporter
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: hpessa-exporter
    app.kubernetes.io/part-of: openshift-hpessa-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hpessa-exporter
subjects:
  - kind: ServiceAccount
    name: hpessa-exporter
    namespace: openshift-hpessa-exporter
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hpessa-exporter-metrics
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - pods
    verbs:
      - get
      - list
      - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hpessa-exporter-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hpessa-exporter-metrics
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: openshift-monitoring
