---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hpessa-exporter
rules:
  - apiGroups:
      - apps
    resources:
      - daemonsets
    verbs:
      - get
      - list
      - create
      - delete
  - apiGroups:
      - ""
    resources:
      - services
      - daemonsets
      - endpoints
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    verbs:
      - create
      - delete
      - get
      - use
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hpessa-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hpessa-exporter
subjects:
  - kind: ServiceAccount
    name: hpessa-exporter
    namespace: openshift-storage-hpessa
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hpessa-exporter
  namespace: openshift-storage-hpessa
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - daemonsets
      - pods
    verbs:
      - get
      - list
      - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hpessa-exporter
  namespace: openshift-storage-hpessa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hpessa-exporter
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: openshift-monitoring
