---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hpessa-exporter
  namespace: openshift-storage-hpessa
  labels:
    app.kubernetes.io/name: hpessa-exporter
    app.kubernetes.io/part-of: openshift-storage-hpessa
rules:
  - apiGroups:
      - apps
    resources:
      - daemonsets
    verbs:
      - get
      - list
      - create
      - delete
  - apiGroups:
      - ""
    resources:
      - services
      - daemonsets
      - pods
      - pods/exec
      - pods/log
    verbs:
      - get
      - list
      - create
      - delete
      - watch
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - prometheusrules
      - podmonitors
    verbs:
      - get
      - list
      - create
      - delete
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    verbs:
      - create
      - delete
      - get
      - use
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hpessa-exporter
  labels:
    app.kubernetes.io/name: hpessa-exporter
    app.kubernetes.io/part-of: openshift-storage-hpessa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hpessa-exporter
subjects:
  - kind: ServiceAccount
    name: hpessa-exporter
    namespace: openshift-storage-hpessa
