---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: hpessa-exporter
  annotations:
    kubernetes.io/description: >
      hpessa-exporter SCC is used for openshift-storage-hpessa

allowPrivilegedContainer: true
allowHostDirVolumePlugin: true
allowHostPID: true
allowHostNetwork: true
allowHostPorts: true
allowHostIPC: false
priority:
readOnlyRootFilesystem: false
requiredDropCapabilities:
  - KILL
  - MKNOD
  - SYS_CHROOT
allowedCapabilities:
  - SYS_ADMIN
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
volumes: ["*"]
users:
  - system:serviceaccount:openshift-storage-hpessa:hpessa-exporter
