---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: hpessa-exporter
    app.kubernetes.io/part-of: openshift-storage-hpessa
  name: hpessa-exporter
  namespace: openshift-storage-hpessa
